version: "3.8"

services:
  api:
    build: .
    network_mode: "host"
    depends_on:
      - postgresdb

  postgresdb:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    network_mode: "host"