version: "3.8"

services:
  api:
    build: .
    ports:
      - "8080:8080"
    links:
      - "postgresdb:database"
    depends_on:
      - postgresdb
    restart: always

  postgresdb:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pg:/var/lib/pg
    ports:
      - "5432:5432"
      -
volumes:
  pg:
    driver: local