version: "3.8"

services:
  api:
    build: .
    ports:
      - "80:80"
    links:
      - "postgresdb:database"
    depends_on:
      - postgresdb

  postgresdb:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"