"""empty message

Revision ID: 58991f87558b
Revises: 
Create Date: 2022-06-26 21:47:58.440021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58991f87558b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
