"""empty message

Revision ID: 76e57ec655a2
Revises: 
Create Date: 2022-06-26 09:52:45.466614

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '76e57ec655a2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('updateDate', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_id'), 'import', ['id'], unique=False)
    op.create_index(op.f('ix_import_updateDate'), 'import', ['updateDate'], unique=False)
    op.create_table('unit',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('type', sa.Enum('OFFER', 'CATEGORY', name='unittype'), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('parentId', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('updateDate', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parentId'], ['unit.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_unit_id'), 'unit', ['id'], unique=False)
    op.create_index(op.f('ix_unit_parentId'), 'unit', ['parentId'], unique=False)
    op.create_index(op.f('ix_unit_updateDate'), 'unit', ['updateDate'], unique=False)
    op.create_table('unit_import',
    sa.Column('import_id', sa.Integer(), nullable=False),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('type', sa.Enum('OFFER', 'CATEGORY', name='unittype'), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('parentId', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('updateDate', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['unit.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['import_id'], ['import.id'], ),
    sa.PrimaryKeyConstraint('import_id', 'id')
    )
    op.create_index(op.f('ix_unit_import_id'), 'unit_import', ['id'], unique=False)
    op.create_index(op.f('ix_unit_import_import_id'), 'unit_import', ['import_id'], unique=False)
    op.create_index(op.f('ix_unit_import_parentId'), 'unit_import', ['parentId'], unique=False)
    op.create_index(op.f('ix_unit_import_updateDate'), 'unit_import', ['updateDate'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_unit_import_updateDate'), table_name='unit_import')
    op.drop_index(op.f('ix_unit_import_parentId'), table_name='unit_import')
    op.drop_index(op.f('ix_unit_import_import_id'), table_name='unit_import')
    op.drop_index(op.f('ix_unit_import_id'), table_name='unit_import')
    op.drop_table('unit_import')
    op.drop_index(op.f('ix_unit_updateDate'), table_name='unit')
    op.drop_index(op.f('ix_unit_parentId'), table_name='unit')
    op.drop_index(op.f('ix_unit_id'), table_name='unit')
    op.drop_table('unit')
    op.drop_index(op.f('ix_import_updateDate'), table_name='import')
    op.drop_index(op.f('ix_import_id'), table_name='import')
    op.drop_table('import')
    # ### end Alembic commands ###
